services:
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_WEB_JVM_OPTS=-Dsonar.jdbc.autoCreateDatabase=true
    ports:
      - "9001:9000"
    volumes:
      - conf:/opt/sonarqube/conf
      - data:/opt/sonarqube/data
      - extensions:/opt/sonarqube/extensions
      - logs:/opt/sonarqube/logs
      - temp:/opt/sonarqube/temp
      - ./plugins:/opt/sonarqube/extensions/plugins


  sonar_db:
    image: postgres:17.0
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  conf:
  data:
  extensions:
  logs:
  temp:
  db_data: